version: "3"
services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - API_HOST_URL=http://api:5000
      - NODE_ENV=production

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_ENVIORMENT: Production
      ASPNETCORE_URLS: http://+:5000
      DATABASE_CONNECTION: "Server=db,1433;Database=JetAnotherEMS;User=sa;Password=Your_password123;"
    depends_on:
      - db
  db:
    image: "microsoft/mssql-server-linux"
    ports:
      - "1433:1433"
    volumes:
      - ./data/mssql:/var/opt/mssql
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
networks:
  default:
    driver: bridge
