version: "3"
services:
  # web:
  #     build: .
  #     ports:
  #         - "8000:80"
  #     depends_on:
  #         - db
  jetanotheremsdb:
    image: "microsoft/mssql-server-linux"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
