export const APP_LOAD = 'APP_LOAD';
export const REDIRECT = 'REDIRECT';
export const ARTICLE_SUBMITTED = 'ARTICLE_SUBMITTED';
export const SETTINGS_SAVED = 'SETTINGS_SAVED';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const SETTINGS_PAGE_UNLOADED = 'SETTINGS_PAGE_UNLOADED';
export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const HOME_PAGE_UNLOADED = 'HOME_PAGE_UNLOADED';
export const ARTICLE_PAGE_LOADED = 'ARTICLE_PAGE_LOADED';
export const ARTICLE_PAGE_UNLOADED = 'ARTICLE_PAGE_UNLOADED';
export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const ARTICLE_FAVORITED = 'ARTICLE_FAVORITED';
export const ARTICLE_UNFAVORITED = 'ARTICLE_UNFAVORITED';
export const SET_PAGE = 'SET_PAGE';
export const APPLY_TAG_FILTER = 'APPLY_TAG_FILTER';
export const CHANGE_TAB = 'CHANGE_TAB';
export const PROFILE_PAGE_LOADED = 'PROFILE_PAGE_LOADED';
export const PROFILE_PAGE_UNLOADED = 'PROFILE_PAGE_UNLOADED';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const REGISTER_WITH_CREDENTIALS = 'REGISTER_WITH_CREDENTIALS';
export const LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED';
export const REGISTER_PAGE_UNLOADED = 'REGISTER_PAGE_UNLOADED';
export const EDITOR_PAGE_LOADED = 'EDITOR_PAGE_LOADED';
export const EDITOR_PAGE_UNLOADED = 'EDITOR_PAGE_UNLOADED';
export const ADD_TAG = 'ADD_TAG';
export const REMOVE_TAG = 'REMOVE_TAG';
export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH';
export const UPDATE_FIELD_EDITOR = 'UPDATE_FIELD_EDITOR';
export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';
export const PROFILE_FAVORITES_PAGE_UNLOADED =
  'PROFILE_FAVORITES_PAGE_UNLOADED';
export const PROFILE_FAVORITES_PAGE_LOADED = 'PROFILE_FAVORITES_PAGE_LOADED';

export const ASYNC_START = 'ASYNC_START';
export const ASYNC_SUCCESS = 'ASYNC_SUCCESS';
export const ASYNC_END = 'ASYNC_END';
export const ASYNC_FAILURE = 'ASYNC_FAILURE';

export const GET_EVENT_AVAILABLE_TICKETS_REQUEST =
  'GET_EVENT_AVAILABLE_TICKETS_REQUEST';
export const GET_EVENT_PARTICIPANTS_REQUEST = 'GET_EVENT_PARTICIPANTS_REQUEST';
export const GET_FEATURED_SCHOOLING_EVENTS_REQUEST =
  'GET_FEATURED_SCHOOLING_EVENTS_REQUEST';
export const GET_SCHOOLING_EVENT_REQUEST = 'GET_SCHOOLING_EVENT_REQUEST';
export const GET_SCHOOLING_EVENT_SCHEDULE_REQUEST =
  'GET_SCHOOLING_EVENT_SCHEDULE_REQUEST';
export const GET_MORE_SCHOOLING_EVENTS = 'GET_MORE_SCHOOLING_EVENTS';
export const CREATE_OR_UPDATE_SCHOOLING_EVENT =
  'CREATE_OR_UPDATE_SCHOOLING_EVENT';
export const POST_CREATE_SCHOOLING_EVENT_REQUEST =
  'POST_CREATE_SCHOOLING_EVENT_REQUEST';
export const PATCH_CREATE_SCHOOLING_EVENT_REQUEST =
  'PATCH_CREATE_SCHOOLING_EVENT_REQUEST';

export const UPDATE_SCHOOLING_EVENT_FILTER = 'UPDATE_SCHOOLING_EVENT_FILTER';

export const POST_LOGIN_WITH_CREDENTIALS_REQUEST =
  'POST_LOGIN_WITH_CREDENTIALS_REQUEST';
export const POST_REGISTER_WITH_CREDENTIALS_REQUEST =
  'POST_REGISTER_WITH_CREDENTIALS_REQUEST';

export const GET_TICKET_FOR_EVENT_REQUEST = 'GET_TICKET_FOR_EVENT_REQUEST';
export const BUY_TICKET_FOR_EVENT_REQUEST = 'BUY_TICKET_FOR_EVENT_REQUEST';
export const CANCEL_TICKET_FOR_EVENT_REQUEST =
  'CANCEL_TICKET_FOR_EVENT_REQUEST';
export const APPROVE_TICKETS_FOR_EVENT_REQUEST =
  'APPROVE_TICKETS_FOR_EVENT_REQUEST';
export const REJECT_TICKETS_FOR_EVENT_REQUEST =
  'REJECT_TICKETS_FOR_EVENT_REQUEST';

export default {
  ASYNC_START,
  ASYNC_SUCCESS,
  ASYNC_FAILURE,
  UPDATE_SCHOOLING_EVENT_FILTER,
  GET_MORE_SCHOOLING_EVENTS
};
